name: Python binaries release
on:
  release:
    types: [created]

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.11
            arch: x64
            artifact-name: python-pack-p311-linux-x86_64.tar.gz

          - os: windows-latest
            python-version: 3.11
            arch: x64
            artifact-name: python-pack-p311-win-x86_64.tar.gz

#          - os: macos-latest
#            python-version: 3.11
#            arch: x64
#            artifact-name: python-pack-p311-mac-x86_64.tar.gz
#
#          - os: macos-latest
#            python-version: 3.11
#            arch: aarch64
#            artifact-name: python-pack-p311-mac-arm_64.tar.gz

    name: Build binary ${{ matrix.artifact-name }} for (python=${{ matrix.python-version }}, os=${{ matrix.os }}, arch=${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: venv
          environment-file: environment.yml

      - name: conda install -n base conda-pack
        run: conda install -n base conda-pack

      - name: conda pack -n venv ...
        run: |
          mkdir -p artifacts
          conda pack -n venv --exclude *.pyc --exclude *.a --compress-level 9 --format tar.gz --output artifacts/${{ matrix.artifact-name }}

      - name: upload-artifact ${{ matrix.artifact-name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ./artifacts/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: md5sum
        run: |
          sudo apt-get install -y coreutils
          cd ./artifacts
          md5sum * > python-pack-md5sums.txt

      - name: attach artifacts to release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: ./artifacts/*
          allowUpdates: true
          removeArtifacts: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          updateOnlyUnreleased: true
